'use client';

import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Comfortaa } from "next/font/google";

const metadata = {
  title: "Video Generator AI",
  description: "Generated by create next app",
};

const comfort = Comfortaa({ subsets: ["latin-ext"], style: "normal", weight: "700" });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={comfort.className}>
          <Provider>
            {children}
          </Provider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
